# Generated by Django 5.2 on 2025-07-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0003_alter_employee_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mob_num',
            field=models.IntegerField(max_length=10),
        ),
    ]
