# Generated by Django 5.2 on 2025-07-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0006_alter_employee_mob_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mob_num',
            field=models.CharField(max_length=10),
        ),
    ]
