# Generated by Django 5.2 on 2025-07-26 09:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0007_alter_employee_mob_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mob_num',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Mobile Number must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
    ]
